locations:

  ### ARRIVAL

  ## Location of the start of the project
  starting_point:
    position:
      x: 3.5  
      y: -4.5  
      z: 0.0
    orientation:
      yaw: 180  # yaw in degrees (converted from ~180 radians)

  ## Location of shelves in the entry point (where there are robot arm and conveyor)
  entry_shelf_raw:
    position:
      x: -1.5  # for all position of the shelf it will be + or - 1 meter from the actual shelf location
      y: -5.5  # The adjusted value will have (adj) next to it
      z: 0.0
    orientation:
      yaw: 180  # yaw in degrees (converted from ~180 radians)

  entry_shelf_half:
    position:
      x: -0.5 # (adj)
      y: -4.5
      z: 0.0
    orientation:
      yaw: 180  # yaw in degrees (converted from ~180 radians)

  entry_shelf_finished:
    position:
      x: -1.5 # (adj)
      y: -3.5
      z: 0.0
    orientation:
      yaw: 180  # yaw in degrees (converted from ~180 radians)

  ## Location of shelves in the transit point (where the shelf is passed from mobile robot 1 to another)

  # In Side (from the entry point)
  # Left Side
  transit_in_shelf_1:
    position:
      x: -2.5
      y: -2.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~1.57 radians)

  transit_in_shelf_2:
    position:
      x: -1.5
      y: -2.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~1.57 radians)

  # Right Side
  transit_in_shelf_3:
    position:
      x: 1.5
      y: -2.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~1.57 radians)

  transit_in_shelf_4:
    position:
      x: 2.5
      y: -2.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~1.57 radians)
      
   transit_in_shelf_5: #the one space in the middle
    position:
      x: -0.5
      y: -2.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~1.57 radians)

  # Out Side (from the entry point)
  # Left Side
  transit_out_shelf_1:
    position:
      x: -2.5
      y: -0.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~-1.57 radians)

  transit_out_shelf_2:
    position:
      x: -1.5
      y: -0.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~-1.57 radians)

  # Right Side
  transit_out_shelf_3:
    position:
      x: 1.5
      y: -0.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~-1.57 radians)

  transit_out_shelf_4:
    position:
      x: 2.5
      y: -0.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~-1.57 radians)
      
    transit_out_shelf_5: #the one space in the middle
    position:
      x: 0
      y: -0.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~1.57 radians)

  # Shelves location for shelf storage

  storage_shelf_1:
    position:
      x: 1.5
      y: -4.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~1.57 radians)

  storage_shelf_2:
    position:
      x: 2.5
      y: -4.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~1.57 radians)

  storage_shelf_3:
    position:
      x: 1.5
      y: -4.5 # (adj)
      z: 0.0
    orientation:
      yaw: -90  # yaw in degrees (converted from ~-1.57 radians)

  storage_shelf_4:
    position:
      x: 2.5
      y: -4.5 # (adj)
      z: 0.0
    orientation:
      yaw: -90  # yaw in degrees (converted from ~-1.57 radians)

  ## Waypoint location for the arrival side

  waypoint_arr_1:
    position:
      x: 0.0
      y: -2.5
      z: 0.0
    orientation:
      yaw: 0.0 # Right (0 radians)

  waypoint_arr_2:
    position:
      x: 0.0
      y: -2.5
      z: 0.0
    orientation:
      yaw: 180  # Left (converted from ~3.14 radians)

  waypoint_arr_3:
    position:
      x: 0.0
      y: -4.5
      z: 0.0
    orientation:
      yaw: 0.0 # Right (0 radians)

  waypoint_arr_4:
    position:
      x: 0.0
      y: -4.5
      z: 0.0
    orientation:
      yaw: 180  # Left (converted from ~3.14 radians)

  ## Boxes location for pickup

  pickup_1:
    position:
      x: -1.5
      y: -4.5
      z: 0.0
    orientation:
      yaw: 180 # Left (converted from ~3.14 radians)

  pickup_2:
    position:
      x: -2.5
      y: -5.5
      z: 0.0
    orientation:
      yaw: 180  # Left (converted from ~3.14 radians)

  pickup_3:
    position:
      x: -2.5
      y: -3.5
      z: 0.0
    orientation:
      yaw: 180  # Left (converted from ~3.14 radians)

  ## Boxes location for pickup but rotated

  pickup_1_rotate:
    position:
      x: -1.5
      y: -4.5
      z: 0.0
    orientation:
      yaw: 0 # Right

  pickup_2_rotate:
    position:
      x: -2.5
      y: -5.5
      z: 0.0
    orientation:
      yaw: 0 # Right

  pickup_3_rotate:
    position:
      x: -2.5
      y: -3.5
      z: 0.0
    orientation:
      yaw: 0 # Right
      
  # Box Delivering in transit
  
  Delivering_1:
    position:
      x: -1.5
      y: -1.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~-1.57 radians)

  Delivering_2:
    position:
      x: -0.5
      y: -1.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~-1.57 radians)
      
   Delivering_3: #the one space in the middle
    position:
      x: 1.5
      y: -1.5 # (adj)
      z: 0.0
    orientation:
      yaw: 90  # yaw in degrees (converted from ~1.57 radians)
      
   ## Waypoint to enter storage area/goal

  waypoint_goal_1:
    position:
      x: 3.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 180 # Left (converted from ~3.14 radians)

  waypoint_goal_2:
    position:
      x: 0.0
      y: 1.5
      z: 0.0
    orientation:
      yaw: 180  # Left (converted from ~3.14 radians)

  waypoint_goal_3:
    position:
      x: 0
      y: 1.5
      z: 0.0
    orientation:
      yaw: 0    # Right
      
  waypoint_goal_4:
    position:
      x: -3.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 0    # Right
      
   ## Dropping the shelves in the storage

  goal_1:
    position:
      x: 2.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 180 # Left (converted from ~3.14 radians)

  goal_2:
    position:
      x: -1.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 180  # Left (converted from ~3.14 radians)

  goal_3:
    position:
      x: 1.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 0    # Right
      
  goal_4:
    position:
      x: -2.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 0    # Right
      
   ## rotate position of goal

  goal_1_rotate:
    position:
      x: 2.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 0    # Right

  goal_2_rotate:
    position:
      x: -1.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 0    # Right

  goal_3_rotate:
    position:
      x: 1.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 180 # Left (converted from ~3.14 radians)
      
  goal_4_rotate:
    position:
      x: -2.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 180 # Left (converted from ~3.14 radians)
      
   ## Exit the shelves

  exit_1:
    position:
      x: 3.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 0    # Right

  exit_2:
    position:
      x: 0.0
      y: 1.5
      z: 0.0
    orientation:
      yaw: 0    # Right

  exit_3:
    position:
      x: 0
      y: 1.5
      z: 0.0
    orientation:
      yaw: 180 # Left (converted from ~3.14 radians)
      
  exit_4:
    position:
      x: -3.5
      y: 1.5
      z: 0.0
    orientation:
      yaw: 180 # Left (converted from ~3.14 radians)     
